### PR TITLE
Fix issue with stale import data

### PR DESCRIPTION
**Pull request by lpinkhard**
This should reduce the likelihood of Unreal Engine requiring a manual import.

### CODE REVIEW

**Comment by lpinkhard** [comment]
The fix would be a bit different whether we're dealing with before or after selective import, hence the request to merge to `package-enhancements` branch.

File: Source/ArticyEditor/Private/ArticyJSONFactory.cpp [hunk 1]
```diff
@@ -369,8 +372,12 @@ bool UArticyJSONFactory::ImportFromFile(const FString& FileName, UArticyImportDa
 #if WITH_EDITORONLY_DATA
     if (bOk && Asset->ImportData)
     {
-        // Important for reimport / tracking: record the source file
-        Asset->ImportData->Update(FileName);
+        // Multi-file merges must record each file at its own index so auto-reimport
+        // matches every one of them, not just the last.
+        const int32 Index = Asset->bMultiFileMerge
+            ? Asset->ImportData->SourceData.SourceFiles.Num()
```
Comment (tim-articy) [inline Source/ArticyEditor/Private/ArticyJSONFactory.cpp]: According to the comment, don't we want to get the FileName's index in SourceFile instead of the amount of entries in SourceFiles?

File: Source/ArticyEditor/Private/ArticyJSONFactory.cpp [hunk 2]
```diff
@@ -369,8 +372,12 @@ bool UArticyJSONFactory::ImportFromFile(const FString& FileName, UArticyImportDa
...
+            : 0;
+        Asset->ImportData->Update(FileName, Index);
```
Comment (tim-articy) [inline Source/ArticyEditor/Private/ArticyJSONFactory.cpp]: This doesn't compile with UE 5.6. I didn't find any matching overload in other versions either.

```
0>ArticyJSONFactory.cpp(380,28): Error C2665 : 'UAssetImportData::Update': no overloaded function could convert all the argument types
0>        Asset->ImportData->Update(FileName, Index);
0>                           ^
0>AssetImportData.h(117,18): Reference  : could be 'void UAssetImportData::Update(const FString &,const FMD5Hash)'
0>	ENGINE_API void Update(const FString& AbsoluteFileName, const FMD5Hash PreComputedHash);
0>	                ^
0>ArticyJSONFactory.cpp(380,28): Reference  : 'void UAssetImportData::Update(const FString &,const FMD5Hash)': cannot convert argument 2 from 'const int32' to 'const FMD5Hash'
0>        Asset->ImportData->Update(FileName, Index);
0>                           ^
0>ArticyJSONFactory.cpp(380,45): Reference  : 'FMD5Hash::FMD5Hash': no overloaded function could convert all the argument types
0>        Asset->ImportData->Update(FileName, Index);
0>                                            ^
0>SecureHash.h(197,1): Reference  : could be 'FMD5Hash::FMD5Hash(FMD5Hash &&)'
0>};
0>^
0>ArticyJSONFactory.cpp(380,45): Reference  : 'FMD5Hash::FMD5Hash(FMD5Hash &&)': cannot convert argument 1 from 'const int32' to 'FMD5Hash &&'
0>        Asset->ImportData->Update(FileName, Index);
0>                                            ^
0>ArticyJSONFactory.cpp(380,45): Reference Reason : cannot convert from 'const int32' to 'FMD5Hash'
0>ArticyJSONFactory.cpp(380,45): Reference  : Conversion requires a second user-defined-conversion operator or constructor
0>SecureHash.h(197,1): Reference  : or       'FMD5Hash::FMD5Hash(const FMD5Hash &)'
0>};
0>^
0>ArticyJSONFactory.cpp(380,45): Reference  : 'FMD5Hash::FMD5Hash(const FMD5Hash &)': cannot convert argument 1 from 'const int32' to 'const FMD5Hash &'
0>        Asset->ImportData->Update(FileName, Index);
0>                                            ^
0>ArticyJSONFactory.cpp(380,45): Reference Reason : cannot convert from 'const int32' to 'const FMD5Hash'
0>ArticyJSONFactory.cpp(380,45): Reference  : Conversion requires a second user-defined-conversion operator or constructor
0>ArticyJSONFactory.cpp(380,45): Reference  : while trying to match the argument list '(const int32)'
0>AssetImportData.h(113,18): Reference  : or       'void UAssetImportData::Update(const FString &,FMD5Hash *)'
0>	ENGINE_API void Update(const FString& AbsoluteFilename, FMD5Hash *Md5Hash = nullptr);
0>	                ^
0>ArticyJSONFactory.cpp(380,28): Reference  : 'void UAssetImportData::Update(const FString &,FMD5Hash *)': cannot convert argument 2 from 'const int32' to 'FMD5Hash *'
0>        Asset->ImportData->Update(FileName, Index);
0>                           ^
0>ArticyJSONFactory.cpp(380,45): Reference  : Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or parenthesized function-style cast
0>        Asset->ImportData->Update(FileName, Index);
0>                                            ^
0>ArticyJSONFactory.cpp(380,28): Reference  : while trying to match the argument list '(const FString, const int32)'
0>        Asset->ImportData->Update(FileName, Index);
```

**Review by tim-articy — CHANGES_REQUESTED** [review]
Doesn't compile with UE 5.6 at least. Check comments for further information.

File: Source/ArticyEditor/Private/ArticyJSONFactory.cpp (hunk 1 above)
Comment (lpinkhard) [reply Source/ArticyEditor/Private/ArticyJSONFactory.cpp]: I replaced the comment to be correct based on the latest changes.

File: Source/ArticyEditor/Private/ArticyJSONFactory.cpp (hunk 2 above)
Comment (lpinkhard) [reply Source/ArticyEditor/Private/ArticyJSONFactory.cpp]: > This doesn't compile with UE 5.6. I didn't find any matching overload in other versions either.
> 
> ```
> 0>ArticyJSONFactory.cpp(380,28): Error C2665 : 'UAssetImportData::Update': no overloaded function could convert all the argument types
> 0>        Asset->ImportData->Update(FileName, Index);
> 0>                           ^
> 0>AssetImportData.h(117,18): Reference  : could be 'void UAssetImportData::Update(const FString &,const FMD5Hash)'
> 0>	ENGINE_API void Update(const FString& AbsoluteFileName, const FMD5Hash PreComputedHash);
> 0>	                ^
> 0>ArticyJSONFactory.cpp(380,28): Reference  : 'void UAssetImportData::Update(const FString &,const FMD5Hash)': cannot convert argument 2 from 'const int32' to 'const FMD5Hash'
> 0>        Asset->ImportData->Update(FileName, Index);
> 0>                           ^
> 0>ArticyJSONFactory.cpp(380,45): Reference  : 'FMD5Hash::FMD5Hash': no overloaded function could convert all the argument types
> 0>        Asset->ImportData->Update(FileName, Index);
> 0>                                            ^
> 0>SecureHash.h(197,1): Reference  : could be 'FMD5Hash::FMD5Hash(FMD5Hash &&)'
> 0>};
> 0>^
> 0>ArticyJSONFactory.cpp(380,45): Reference  : 'FMD5Hash::FMD5Hash(FMD5Hash &&)': cannot convert argument 1 from 'const int32' to 'FMD5Hash &&'
> 0>        Asset->ImportData->Update(FileName, Index);
> 0>                                            ^
> 0>ArticyJSONFactory.cpp(380,45): Reference Reason : cannot convert from 'const int32' to 'FMD5Hash'
> 0>ArticyJSONFactory.cpp(380,45): Reference  : Conversion requires a second user-defined-conversion operator or constructor
> 0>SecureHash.h(197,1): Reference  : or       'FMD5Hash::FMD5Hash(const FMD5Hash &)'
> 0>};
> 0>^
> 0>ArticyJSONFactory.cpp(380,45): Reference  : 'FMD5Hash::FMD5Hash(const FMD5Hash &)': cannot convert argument 1 from 'const int32' to 'const FMD5Hash &'
> 0>        Asset->ImportData->Update(FileName, Index);
> 0>                                            ^
> 0>ArticyJSONFactory.cpp(380,45): Reference Reason : cannot convert from 'const int32' to 'const FMD5Hash'
> 0>ArticyJSONFactory.cpp(380,45): Reference  : Conversion requires a second user-defined-conversion operator or constructor
> 0>ArticyJSONFactory.cpp(380,45): Reference  : while trying to match the argument list '(const int32)'
> 0>AssetImportData.h(113,18): Reference  : or       'void UAssetImportData::Update(const FString &,FMD5Hash *)'
> 0>	ENGINE_API void Update(const FString& AbsoluteFilename, FMD5Hash *Md5Hash = nullptr);
> 0>	                ^
> 0>ArticyJSONFactory.cpp(380,28): Reference  : 'void UAssetImportData::Update(const FString &,FMD5Hash *)': cannot convert argument 2 from 'const int32' to 'FMD5Hash *'
> 0>        Asset->ImportData->Update(FileName, Index);
> 0>                           ^
> 0>ArticyJSONFactory.cpp(380,45): Reference  : Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or parenthesized function-style cast
> 0>        Asset->ImportData->Update(FileName, Index);
> 0>                                            ^
> 0>ArticyJSONFactory.cpp(380,28): Reference  : while trying to match the argument list '(const FString, const int32)'
> 0>        Asset->ImportData->Update(FileName, Index);
> ```

My apologies. The PR was missing the last commit where I fixed this.

**Review by tim-articy — APPROVED** [review]
Classic :) LGTM now
